/* eslint-disable linebreak-style */
module.exports = {
  products: [
    {
      _id: '111111111111111111111111',
      name: "Regata Nike Legend 2.0 Tee Masculina - Preto+Branco",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 149.99,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Calça AEROREADY Sereno Slim Tapered Cut 3-Stripes",
      category: "Pants",
      image: "/images/product-2.jpg",
      price: 249.99,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 8,
      countInStock: 12,
    },
    {
      _id: "3",
      name: "Moletom Fila Letter New I Preto - Preto",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 119.99,
      brand: "Fila",
      rating: 5,
      numReviews: 1,
      countInStock: 4,
    },
    {
      _id: "4",
      name: "Camiseta Adidas Designed to Move Sport 3 Listras Masculina - Preto",
      category: 'Shirts',
      image: "/images/product-4.jpg",
      price: 89.99,
      brand: "Adidas",
      rating: 4.51,
      numReviews: 117,
      countInStock: 7,
    },
    {
      _id: "5",
      name: "Camiseta Nike Essentials Icon Futura Feminina - Rosa Claro",
      category: "Shirts",
      image: "/images/product-5.jpg",
      price: 85.49,
      brand: "Nike",
      rating: 4.67,
      numReviews: 528,
      countInStock: 3,
    },
    {
      _id: "6",
      name: "Camiseta Puma Cropped Small Logo Feminina - Branco",
      category: "Shirts",
      image: "/images/product-6.jpg",
      price: 75.49,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
    },
  ],
};
